--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: graf
  name: grafana-svc
spec: 
  ports: 
    - nodePort: 31000
      port: 3000
      targetPort: 3000
  selector: 
    app: graf
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafvol
  labels:
    app: graf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: graf
spec:
  selector:
    matchLabels:
      app: graf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: graf
    spec:
      containers:
      - name: graf-cont
        image: kapil1305/grafana
        volumeMounts:
        - name: graf-vol1
          mountPath: /var/lib/grafana
        ports:
        - containerPort: 3000
      volumes:
      - name: graf-vol1
        persistentVolumeClaim:
          claimName: grafvol      
     
---






